// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/handler/order_handler/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/http/handler/order_handler/handler.go -destination=internal/delivery/http/handler/order_handler/mock/service_mock.go -package=mock_orderhandler
//

// Package mock is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	order "github.com/GarikMirzoyan/gophermart/internal/domain/order"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockService) AddOrder(ctx context.Context, userID int, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, userID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockServiceMockRecorder) AddOrder(ctx, userID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockService)(nil).AddOrder), ctx, userID, number)
}

// GetOrdersByUser mocks base method.
func (m *MockService) GetOrdersByUser(ctx context.Context, userID int) ([]*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUser", ctx, userID)
	ret0, _ := ret[0].([]*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUser indicates an expected call of GetOrdersByUser.
func (mr *MockServiceMockRecorder) GetOrdersByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUser", reflect.TypeOf((*MockService)(nil).GetOrdersByUser), ctx, userID)
}

// ProcessPendingOrders mocks base method.
func (m *MockService) ProcessPendingOrders(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessPendingOrders", ctx)
}

// ProcessPendingOrders indicates an expected call of ProcessPendingOrders.
func (mr *MockServiceMockRecorder) ProcessPendingOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPendingOrders", reflect.TypeOf((*MockService)(nil).ProcessPendingOrders), ctx)
}
