// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/http/handler/balance_handler/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/delivery/http/handler/balance_handler/handler.go -destination=internal/delivery/http/handler/balance_handler/mock/balance_mock.go -package=mock_orderhandler
//

// Package mock is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	balance "github.com/GarikMirzoyan/gophermart/internal/domain/balance"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddBalance mocks base method.
func (m *MockService) AddBalance(ctx context.Context, userID int, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBalance", ctx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBalance indicates an expected call of AddBalance.
func (mr *MockServiceMockRecorder) AddBalance(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBalance", reflect.TypeOf((*MockService)(nil).AddBalance), ctx, userID, amount)
}

// GetBalance mocks base method.
func (m *MockService) GetBalance(ctx context.Context, userID int) (*balance.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(*balance.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockService)(nil).GetBalance), ctx, userID)
}
