// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/withdrawal/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/withdrawal/repository.go -destination=internal/domain/withdrawal/mocks/repository_mock.go -package=mock_withdrawal
//

// Package mock is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	withdrawal "github.com/GarikMirzoyan/gophermart/internal/domain/withdrawal"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetTotalWithdrawn mocks base method.
func (m *MockRepository) GetTotalWithdrawn(ctx context.Context, userID int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalWithdrawn", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalWithdrawn indicates an expected call of GetTotalWithdrawn.
func (mr *MockRepositoryMockRecorder) GetTotalWithdrawn(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalWithdrawn", reflect.TypeOf((*MockRepository)(nil).GetTotalWithdrawn), ctx, userID)
}

// GetUserWithdrawals mocks base method.
func (m *MockRepository) GetUserWithdrawals(ctx context.Context, userID int) ([]*withdrawal.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]*withdrawal.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockRepositoryMockRecorder) GetUserWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockRepository)(nil).GetUserWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockRepository) Withdraw(ctx context.Context, userID int, order string, sum float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, order, sum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockRepositoryMockRecorder) Withdraw(ctx, userID, order, sum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockRepository)(nil).Withdraw), ctx, userID, order, sum)
}
