// Code generated by MockGen. DO NOT EDIT.
// Source: internal/loyalty/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/loyalty/client.go -destination=internal/loyalty/mocks/client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	loyalty "github.com/GarikMirzoyan/gophermart/internal/loyalty"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAccrual mocks base method.
func (m *MockClient) GetAccrual(ctx context.Context, orderNumber string) (*loyalty.OrderAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(*loyalty.OrderAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccrual indicates an expected call of GetAccrual.
func (mr *MockClientMockRecorder) GetAccrual(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccrual", reflect.TypeOf((*MockClient)(nil).GetAccrual), ctx, orderNumber)
}
